### ISSUE TITLE
Skeleton Column Format Issues with Admin Prices view

### ISSUE THREAD

**Issue by aegixx** [spree-contrib/spree_multi_currency#35]
You can reproduce by creating a sample spree application w/ spree_multi_currency and loading the sample data: http://localhost:3000/admin/products/ruby-on-rails-baseball-jersey/prices

![image](https://cloud.githubusercontent.com/assets/7032283/5673044/c6ea6c1c-975c-11e4-9b13-0f5720b11e07.png)

**Comment by aegixx** [comment]
![image](https://cloud.githubusercontent.com/assets/7032283/5729571/eb783aac-9b38-11e4-864a-9321c7e137e5.png)

**Comment by futhr** [comment]
This has been fixed with 9be4bb8 and 3364a138943fbc651b1be74e4d5c13bb5b112ad5 in `2-3-stable` and `2-4-stable` branches. This bug should not apply to `master` branch due to layout changes in 36f76c384182b44ada81937a134871ae0ddb349b.
