### ISSUE TITLE
is it compatible with spree backend 2.4 ?

### ISSUE THREAD

**Issue by FadliKun** [spree-contrib/spree_multi_currency#49]
is spree_multi_currency compatible with spree backend 2.4 ?

**Comment by futhr** [comment]
Hi @FadliKun you have the https://github.com/spree-contrib/spree_multi_currency/tree/2-4-stable branch, happy coding!

**Comment by FadliKun** [comment]
ya i'm forget to check the branch.. tq mr futhr
