### ISSUE TITLE
Can't calculate shipping rates 

### ISSUE THREAD

**Issue by justinemar** [spree-contrib/spree_multi_currency#71]
This error occurs only when i select a currency other than USD from the selector. If i save and continue from the address form i will get this error. 
> We are unable to calculate shipping rates for the selected items

The checkout process will only proceed if i choose USD from the currency selector.

This is spree 3.3

**Comment by AlekseyArder** [comment]
+1

**Comment by AlekseyArder** [comment]
I found that you need to add Shipping Methods with each currency that you have (e.g., UPS Ground (USD), UPS Ground (EUR), etc.)

**Comment by mdavo6** [comment]
I ran into the same issue. Adding shipping methods using each currency you accept should fix it up, as suggested by @AlekseyArder . You should also ensure that the country you enter as the shipping address is covered by your shipping methods with the selected currency.
