### ISSUE TITLE
allow_currency_change preference not defined

### ISSUE THREAD

**Issue by MatthewKennedy** [spree-contrib/spree_multi_currency#96]
Using a fresh setup of:
Rails 6
Ruby 2.6.5
Spree 4.0.3

I get the error `allow_currency_change preference not defined `

Any suggestions?

**Comment by MatthewKennedy** [comment]
This seems to fix if you set autoloader to classic mode and re run the extension bundle installer.

I don’t understand exactly why.

**Comment by Tashows** [comment]
I am on rails 5.2.1 and am getting the same issue.

**Comment by MatthewKennedy** [comment]
@Tashows 

I managed to get round it by using the method in the linked file:
https://github.com/spree-four/spree_multi_currency/blob/master/lib/spree_multi_currency/engine.rb

I don't know if it's the right way to do it or not.
